development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: cooper_development
  pool: 10
  username: root
  password: ""
  host: localhost
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: cooper_production 
  pool: 10
  username: root
  password: ""
  host: localhost
  socket: /tmp/mysql.sock
